server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtest?characterEncoding=utf8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  #type-aliases-package: com.luo.study003.entity
  #config-location: classpath:mybatisConfig.xml

#showsql
logging:
  level:
    com:
      luo:
        study003:
          mapper: debug